//Maya ASCII 2018ff08 scene
//Name: test.ma
//Last modified: Mon, Oct 15, 2018 03:58:12 PM
//Codeset: 1252
requires maya "2018ff08";
requires -nodeType "aiStandardSurface" "mtoa" "3.0.0.2";
requires "stereoCamera" "10.0";
requires "stereoCamera" "10.0";
currentUnit -l centimeter -a degree -t film;
fileInfo "application" "maya";
fileInfo "product" "Maya 2018";
fileInfo "version" "2018";
fileInfo "cutIdentifier" "201804211841-f3d65dda2a";
fileInfo "osv" "Microsoft Windows 8 Home Premium Edition, 64-bit  (Build 9200)\n";
fileInfo "license" "education";
createNode place2dTexture -n "place2dTexture1";
	rename -uid "B44BE0A1-4884-803D-09C0-13B6014DCBB8";
createNode file -n "file1";
	rename -uid "1D871433-4B36-2284-AECD-B28902B0D096";
	setAttr ".ftn" -type "string" "C:/Users/etudiant/Documents/clarrisse_alshader_tests/TEST_RENDU_CLARISSE//sourceimages/Concrete21/3K/Concrete21_COL_VAR2_3K.jpg";
	setAttr ".cs" -type "string" "sRGB";
createNode file -n "file2";
	rename -uid "8C4FA8B8-473E-C570-9C3A-71BC2856A71D";
	setAttr ".ftn" -type "string" "C:/Users/etudiant/Documents/clarrisse_alshader_tests/TEST_RENDU_CLARISSE//sourceimages/Concrete21/3K/Concrete21_GLOSS_3K.jpg";
	setAttr ".cs" -type "string" "Raw";
createNode remapColor -n "remapColor1";
	rename -uid "D40994B8-4ABB-1887-76B4-16A07BBB9E1F";
	setAttr -s 3 ".r[0:2]"  0 0 1 1 1 1 0.5043478 0.56 1;
	setAttr -s 3 ".g[0:2]"  0 0 1 1 1 1 0.51304346 0.5 1;
	setAttr -s 3 ".b[0:2]"  0 0 1 1 1 1 0.39130434 0.34 1;
createNode place2dTexture -n "place2dTexture2";
	rename -uid "15A7A8F4-4621-5798-2A98-29A40D5E1A89";
createNode reverse -n "reverse1";
	rename -uid "08CF066D-4909-3D37-2DEB-B99DCB15BE03";
createNode aiStandardSurface -n "CONCRETE";
	rename -uid "DFA75AC9-478B-B90C-0171-32AF18DBC7AF";
	setAttr ".base" 1;
createNode shadingEngine -n "aiStandardSurface1SG";
	rename -uid "50719386-4C81-4EE7-F908-3BAF9671553B";
	addAttr -ci true -h true -sn "aal" -ln "attributeAliasList" -dt "attributeAlias";
	setAttr ".ihi" 0;
	setAttr -s 2 ".dsm";
	setAttr ".ro" yes;
	setAttr -s 2 ".aovs";
	setAttr ".aovs[0].aov_name" -type "string" "specular_direct";
	setAttr ".aovs[1].aov_name" -type "string" "specular_indirect";
	setAttr ".aal" -type "attributeAlias" {"ai_aov_specular_direct","aiCustomAOVs[0]"
		,"ai_aov_specular_indirect","aiCustomAOVs[1]"} ;
createNode bump2d -n "bump2d1";
	rename -uid "3C341F3B-429C-B0CC-B185-168B99EC3298";
	setAttr ".bi" 1;
	setAttr ".vc1" -type "float3" 0 9.9999997e-06 0 ;
	setAttr ".vc2" -type "float3" 9.9999997e-06 9.9999997e-06 0 ;
createNode file -n "file3";
	rename -uid "2994802E-4EEC-A85A-2135-FDBFD08085D5";
	setAttr ".ail" yes;
	setAttr ".ftn" -type "string" "C:/Users/etudiant/Documents/clarrisse_alshader_tests/TEST_RENDU_CLARISSE//sourceimages/Concrete21/3K/Concrete21_NRM_3K.jpg";
	setAttr ".cs" -type "string" "Raw";
createNode place2dTexture -n "place2dTexture3";
	rename -uid "2591E4A4-4991-A6AF-A335-1EBDD641107E";
createNode materialInfo -n "materialInfo1";
	rename -uid "D98F3307-4AB0-91BC-923D-609F9646F9D6";
createNode lightLinker -s -n "lightLinker1";
	rename -uid "E82ED4D8-4D0E-743C-E522-46874E3F0061";
	setAttr -s 6 ".lnk";
	setAttr -s 6 ".slnk";
select -ne :time1;
	setAttr ".o" 1;
	setAttr ".unw" 1;
select -ne :hardwareRenderingGlobals;
	setAttr ".otfna" -type "stringArray" 22 "NURBS Curves" "NURBS Surfaces" "Polygons" "Subdiv Surface" "Particles" "Particle Instance" "Fluids" "Strokes" "Image Planes" "UI" "Lights" "Cameras" "Locators" "Joints" "IK Handles" "Deformers" "Motion Trails" "Components" "Hair Systems" "Follicles" "Misc. UI" "Ornaments"  ;
	setAttr ".otfva" -type "Int32Array" 22 0 1 1 1 1 1
		 1 1 1 0 0 0 0 0 0 0 0 0
		 0 0 0 0 ;
	setAttr ".fprt" yes;
select -ne :renderPartition;
	setAttr -s 6 ".st";
select -ne :renderGlobalsList1;
select -ne :defaultShaderList1;
	setAttr -s 8 ".s";
select -ne :postProcessList1;
	setAttr -s 2 ".p";
select -ne :defaultRenderUtilityList1;
	setAttr -s 16 ".u";
select -ne :defaultRenderingList1;
select -ne :lightList1;
	setAttr -s 2 ".l";
select -ne :defaultTextureList1;
	setAttr -s 8 ".tx";
select -ne :initialShadingGroup;
	addAttr -ci true -h true -sn "aal" -ln "attributeAliasList" -dt "attributeAlias";
	setAttr ".ro" yes;
	setAttr -s 2 ".aovs";
	setAttr ".aovs[0].aov_name" -type "string" "specular_direct";
	setAttr ".aovs[1].aov_name" -type "string" "specular_indirect";
	setAttr ".aal" -type "attributeAlias" {"ai_aov_specular_direct","aiCustomAOVs[0].aovName"
		,"ai_aov_specular_indirect","aiCustomAOVs[1].aovName"} ;
select -ne :initialParticleSE;
	addAttr -ci true -h true -sn "aal" -ln "attributeAliasList" -dt "attributeAlias";
	setAttr ".ro" yes;
	setAttr -s 2 ".aovs";
	setAttr ".aovs[0].aov_name" -type "string" "specular_direct";
	setAttr ".aovs[1].aov_name" -type "string" "specular_indirect";
	setAttr ".aal" -type "attributeAlias" {"ai_aov_specular_direct","aiCustomAOVs[0].aovName"
		,"ai_aov_specular_indirect","aiCustomAOVs[1].aovName"} ;
select -ne :defaultRenderGlobals;
	setAttr ".ren" -type "string" "arnold";
	setAttr ".outf" 51;
	setAttr ".imfkey" -type "string" "exr";
select -ne :defaultResolution;
	setAttr ".pa" 1;
select -ne :defaultLightSet;
	setAttr -s 2 ".dsm";
select -ne :hardwareRenderGlobals;
	setAttr ".ctrs" 256;
	setAttr ".btrs" 512;
connectAttr ":defaultColorMgtGlobals.cme" "file1.cme";
connectAttr ":defaultColorMgtGlobals.cfe" "file1.cmcf";
connectAttr ":defaultColorMgtGlobals.cfp" "file1.cmcp";
connectAttr ":defaultColorMgtGlobals.wsn" "file1.ws";
connectAttr "place2dTexture1.c" "file1.c";
connectAttr "place2dTexture1.tf" "file1.tf";
connectAttr "place2dTexture1.rf" "file1.rf";
connectAttr "place2dTexture1.mu" "file1.mu";
connectAttr "place2dTexture1.mv" "file1.mv";
connectAttr "place2dTexture1.s" "file1.s";
connectAttr "place2dTexture1.wu" "file1.wu";
connectAttr "place2dTexture1.wv" "file1.wv";
connectAttr "place2dTexture1.re" "file1.re";
connectAttr "place2dTexture1.of" "file1.of";
connectAttr "place2dTexture1.r" "file1.ro";
connectAttr "place2dTexture1.n" "file1.n";
connectAttr "place2dTexture1.vt1" "file1.vt1";
connectAttr "place2dTexture1.vt2" "file1.vt2";
connectAttr "place2dTexture1.vt3" "file1.vt3";
connectAttr "place2dTexture1.vc1" "file1.vc1";
connectAttr "place2dTexture1.o" "file1.uv";
connectAttr "place2dTexture1.ofs" "file1.fs";
connectAttr ":defaultColorMgtGlobals.cme" "file2.cme";
connectAttr ":defaultColorMgtGlobals.cfe" "file2.cmcf";
connectAttr ":defaultColorMgtGlobals.cfp" "file2.cmcp";
connectAttr ":defaultColorMgtGlobals.wsn" "file2.ws";
connectAttr "place2dTexture2.c" "file2.c";
connectAttr "place2dTexture2.tf" "file2.tf";
connectAttr "place2dTexture2.rf" "file2.rf";
connectAttr "place2dTexture2.mu" "file2.mu";
connectAttr "place2dTexture2.mv" "file2.mv";
connectAttr "place2dTexture2.s" "file2.s";
connectAttr "place2dTexture2.wu" "file2.wu";
connectAttr "place2dTexture2.wv" "file2.wv";
connectAttr "place2dTexture2.re" "file2.re";
connectAttr "place2dTexture2.of" "file2.of";
connectAttr "place2dTexture2.r" "file2.ro";
connectAttr "place2dTexture2.n" "file2.n";
connectAttr "place2dTexture2.vt1" "file2.vt1";
connectAttr "place2dTexture2.vt2" "file2.vt2";
connectAttr "place2dTexture2.vt3" "file2.vt3";
connectAttr "place2dTexture2.vc1" "file2.vc1";
connectAttr "place2dTexture2.o" "file2.uv";
connectAttr "place2dTexture2.ofs" "file2.fs";
connectAttr "file1.oc" "remapColor1.cl";
connectAttr "file2.oa" "reverse1.ix";
connectAttr "remapColor1.oc" "CONCRETE.base_color";
connectAttr "reverse1.ox" "CONCRETE.specular_roughness";
connectAttr "bump2d1.o" "CONCRETE.n";
connectAttr "CONCRETE.out" "aiStandardSurface1SG.ss";
connectAttr "pSphereShape1.iog" "aiStandardSurface1SG.dsm" -na;
connectAttr "file3.oa" "bump2d1.bv";
connectAttr ":defaultColorMgtGlobals.cme" "file3.cme";
connectAttr ":defaultColorMgtGlobals.cfe" "file3.cmcf";
connectAttr ":defaultColorMgtGlobals.cfp" "file3.cmcp";
connectAttr ":defaultColorMgtGlobals.wsn" "file3.ws";
connectAttr "place2dTexture3.c" "file3.c";
connectAttr "place2dTexture3.tf" "file3.tf";
connectAttr "place2dTexture3.rf" "file3.rf";
connectAttr "place2dTexture3.mu" "file3.mu";
connectAttr "place2dTexture3.mv" "file3.mv";
connectAttr "place2dTexture3.s" "file3.s";
connectAttr "place2dTexture3.wu" "file3.wu";
connectAttr "place2dTexture3.wv" "file3.wv";
connectAttr "place2dTexture3.re" "file3.re";
connectAttr "place2dTexture3.of" "file3.of";
connectAttr "place2dTexture3.r" "file3.ro";
connectAttr "place2dTexture3.n" "file3.n";
connectAttr "place2dTexture3.vt1" "file3.vt1";
connectAttr "place2dTexture3.vt2" "file3.vt2";
connectAttr "place2dTexture3.vt3" "file3.vt3";
connectAttr "place2dTexture3.vc1" "file3.vc1";
connectAttr "place2dTexture3.o" "file3.uv";
connectAttr "place2dTexture3.ofs" "file3.fs";
connectAttr "aiStandardSurface1SG.msg" "materialInfo1.sg";
connectAttr "CONCRETE.msg" "materialInfo1.m";
connectAttr "CONCRETE.msg" "materialInfo1.t" -na;
relationship "link" ":lightLinker1" ":initialShadingGroup.message" ":defaultLightSet.message";
relationship "link" ":lightLinker1" ":initialParticleSE.message" ":defaultLightSet.message";
relationship "link" ":lightLinker1" "aiStandardSurface1SG.message" ":defaultLightSet.message";
relationship "shadowLink" ":lightLinker1" ":initialShadingGroup.message" ":defaultLightSet.message";
relationship "shadowLink" ":lightLinker1" ":initialParticleSE.message" ":defaultLightSet.message";
relationship "shadowLink" ":lightLinker1" "aiStandardSurface1SG.message" ":defaultLightSet.message";
connectAttr "aiStandardSurface1SG.pa" ":renderPartition.st" -na;
connectAttr "CONCRETE.msg" ":defaultShaderList1.s" -na;
connectAttr "place2dTexture1.msg" ":defaultRenderUtilityList1.u" -na;
connectAttr "place2dTexture2.msg" ":defaultRenderUtilityList1.u" -na;
connectAttr "reverse1.msg" ":defaultRenderUtilityList1.u" -na;
connectAttr "place2dTexture3.msg" ":defaultRenderUtilityList1.u" -na;
connectAttr "bump2d1.msg" ":defaultRenderUtilityList1.u" -na;
connectAttr "remapColor1.msg" ":defaultRenderUtilityList1.u" -na;
connectAttr "file1.msg" ":defaultTextureList1.tx" -na;
connectAttr "file2.msg" ":defaultTextureList1.tx" -na;
connectAttr "file3.msg" ":defaultTextureList1.tx" -na;
// End of test.ma
